### ISSUE TITLE
I have a problem about reCAPTCHA

### ISSUE THREAD

**Issue by akkradet** [abedputra/Dnato-system-login#3]
I created Site key and Secret key reCAPTCHA but show error

Error...! Google Recaptcha UnSuccessful!

help me remove reCAPTCHA

**Comment by abedputra** [comment]
Hi, Please change some code from [this link](https://github.com/abedputra/Dnato-system-login/commit/fe17eda0f3bf75249ad6c6fd22b5bb1c1de66740)

Next version will be able to turn off/on recaptcha, but it will be soon.

**Comment by akkradet** [comment]
thank you for version off recapcha

**Comment by abedputra** [comment]
Hi akkradet,

Please update new Dnato.
New Feature:
-Account Secure (Notification to Review Activity Log In, Will Sent via Your Email like Google) 
-Active or Inactive Recaptcha
-Add Settings 
-Add Theme 

Thank You

**Comment by akkradet** [comment]
have a lot of bugs 
- [controllers/Main.php](https://github.com/abedputra/Dnato-system-login/blob/master/application/controllers/Main.php)
- Register not found **libraries/Email.php**
- login white page

**Comment by abedputra** [comment]
Hi,
Thanks for report.

The problem is because when I was pull Dnato in github.

Please update [controllers/Main.php](https://github.com/abedputra/Dnato-system-login/commit/bb22133ecaf03c0bd0292f9c0fbf1c5d5a416f19)

make sure delete old version of SQL and add new SQL.

Thank U

**Comment by akkradet** [comment]
It's Work, Nice!

**Comment by akkradet** [comment]
Now I found bug delete Admin
I will continue to develop.  Thank you somuch
