### ISSUE TITLE
Call to undefined function mcrypt_create_iv()

### ISSUE THREAD

**Issue by thuyvu89** [abedputra/Dnato-system-login#5]
I changed my admin password and received an error
PHP version: 7.2.3
Server version: Apache/2.4.18

`An uncaught Exception was encountered
Type: Error

Message: Call to undefined function mcrypt_create_iv()

Filename: /application/libraries/Password.php

Line Number: 31

Backtrace:

File: application/controllers/Main.php
Line: 301
Function: create_hash`

**Comment by helmipauzi** [comment]
I have same problem to. when add new user with admin role this error has show

An uncaught Exception was encountered
Type: Error

Message: Call to undefined function mcrypt_create_iv()

Filename: C:\xampp\htdocs\groopis\application\libraries\Password.php

Line Number: 31

Backtrace:

File: C:\xampp\htdocs\groopis\application\controllers\Main.php
Line: 399
Function: create_hash

File: C:\xampp\htdocs\groopis\index.php
Line: 315
Function: require_once

**Comment by abedputra** [comment]
thanks guys for report, please update the library of password, thanks..
https://github.com/abedputra/Dnato-system-login/commit/ecee2a8f3a94e16457be61429118f288ba1908d1

Abed P
